-- User Management System - database setup
-- Run:  mysql -u root -p < database/schema.sql     (or paste into MySQL Workbench)

CREATE DATABASE IF NOT EXISTS user_management;
USE user_management;

CREATE TABLE IF NOT EXISTS users (
    id         INT PRIMARY KEY AUTO_INCREMENT,           -- generated by MySQL, never supplied by us
    name       VARCHAR(100) NOT NULL,
    email      VARCHAR(100) NOT NULL UNIQUE,             -- UNIQUE => duplicate emails are rejected by the DB itself
    password   VARCHAR(255) NOT NULL,                    -- plaintext ONLY for this prototype (see README)
    phone      VARCHAR(20),
    role       VARCHAR(20) NOT NULL DEFAULT 'USER',      -- 'ADMIN' or 'USER'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Test accounts (INSERT IGNORE = safe to run the script more than once)
INSERT IGNORE INTO users (name, email, password, phone, role)
VALUES ('Admin', 'admin@gmail.com', 'admin123', '9999999999', 'ADMIN');

INSERT IGNORE INTO users (name, email, password, phone, role)
VALUES ('Test User', 'user@gmail.com', 'user123', '8888888888', 'USER');
